module.exports = {
	SAVE_CONTACT: 'SAVE_CONTACT',
	RECEIVE_CONTACTS: 'RECEIVE_CONTACTS',
	REMOVE_CONTACT: 'REMOVE_CONTACT',
	UPDATE_CONTACT: 'UPDATE_CONTACT',
	EDIT_CONTACT: 'EDIT_CONTACT',
	CALL_SAVE_CONTACT: 'CALL_SAVE_CONTACT',
	CALL_RECEIVE_CONTACTS: 'CALL_RECEIVE_CONTACTS',
	CALL_REMOVE_CONTACT: 'CALL_REMOVE_CONTACT',
	CALL_UPDATE_CONTACT: 'CALL_UPDATE_CONTACT'
}